redis:
  image: redis:3.0.3
  ports:
    - 6379:6379
  volumes:
    - ./data/redis:/data

registry:
  image: registry:2.1.1
  ports:
    - 5000:5000
  volumes:
    - ./data/registry:/var/lib/registry
